package biz.flowinn.product.logistics.domain.enumeration;

/**
 * The MoloniEndpoints enumeration.
 */
public enum MoloniEndpoints {
    INVOICES,
    RECEIPTS,
    CREDIT_NOTES,
    DEBIT_NOTES,
    SIMPLIFIED_INVOICES,
    DELIVERY_NOTES,
    BILLS_OF_LADING,
    OWN_ASSETS_MOVEMENT_GUIDES,
    WAYBILLS,
    CUSTOMER_RETURN_NOTE,
    ESTIMATES,
    INTERNAL_DOCUMENTS,
    INVOICE_RECEIPTS,
    PAYMENT_RETURNS,
    PURCHASE_ORDER,
    SUPPLIER_PURCHASE_ORDER,
    SUPPLIER_INVOICES,
    SUPPLIER_SIMPLIFIED_INVOICES,
    SUPPLIER_CREDIT_NOTES,
    SUPPLIER_DEBIT_NOTES,
    SUPPLIER_RETURN_NOTES,
    SUPPLIER_RECEIPTS,
    SUPPLIER_WARRANTY_REQUESTS,
    GLOBAL_GUIDES,
}
